# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  tag: '$(Build.BuildId)'


pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: BuildAndPush
    jobs:
      - job: BuildJob
        displayName: Build
        steps:
           
          - task: Docker@2
            inputs:
              containerRegistry: 'DockerSVC'
              repository: 'umakanth455/user-management'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(tag)'
